CRITICAL - 2023-10-08 02:58:34 --> Undefined variable $categories
in APPPATH\Views\home_view.php on line 60.
 1 APPPATH\Views\home_view.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $categories', 'D:\\XAMPP_NEW\\htdocs\\Codeigniter4\\app\\Views\\home_view.php', 60)
 2 SYSTEMPATH\View\View.php(226): include('D:\\XAMPP_NEW\\htdocs\\Codeigniter4\\app\\Views\\home_view.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('home_view', [], true)
 5 APPPATH\Controllers\HomeController.php(9): view('home_view')
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 03:57:07 --> Undefined variable $categories
in APPPATH\Views\home_view.php on line 60.
 1 APPPATH\Views\home_view.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $categories', 'D:\\XAMPP_NEW\\htdocs\\Codeigniter4\\app\\Views\\home_view.php', 60)
 2 SYSTEMPATH\View\View.php(226): include('D:\\XAMPP_NEW\\htdocs\\Codeigniter4\\app\\Views\\home_view.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('home_view', [], true)
 5 APPPATH\Controllers\HomeController.php(9): view('home_view')
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:20:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:20:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:21:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:21:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:21:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:21:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:21:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:21:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:23:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:23:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:24:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:24:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:24:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:24:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:48:46 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:48:46 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:48:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:48:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 04:53:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 04:53:02 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(9): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-08 05:03:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP_NEW\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP_NEW\htdocs\Codeigniter4\app\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
#5 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(919): App\Controllers\HomeController->index()
#6 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
#7 D:\XAMPP_NEW\htdocs\Codeigniter4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP_NEW\htdocs\Codeigniter4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-08 05:03:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Categories`', [], false)
 3 APPPATH\Models\news_modal.php(11): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\HomeController.php(10): App\Models\news_modal->getCategories()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 05:07:50 --> Invalid file: "news/index.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('news/index.php')
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('news/index', [], true)
 3 APPPATH\Controllers\HomeController.php(11): view('news/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 05:11:27 --> Invalid file: "news/index.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('news/index.php')
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('news/index', [], true)
 3 APPPATH\Controllers\HomeController.php(11): view('news/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 05:22:41 --> Invalid file: "news/home_view.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('news/home_view.php')
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('news/home_view', [], true)
 3 APPPATH\Controllers\HomeController.php(11): view('news/home_view', [...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 05:23:30 --> Undefined variable $articles
in APPPATH\Views\home_view.php on line 73.
 1 APPPATH\Views\home_view.php(73): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $articles', 'D:\\XAMPP_NEW\\htdocs\\Codeigniter4\\app\\Views\\home_view.php', 73)
 2 SYSTEMPATH\View\View.php(226): include('D:\\XAMPP_NEW\\htdocs\\Codeigniter4\\app\\Views\\home_view.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('home_view', [], true)
 5 APPPATH\Controllers\HomeController.php(11): view('home_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\HomeController->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
